### ISSUE TITLE
question:

### ISSUE THREAD

**Issue by joeblew99** [utamaro/wsrpc#1]
This looks nice and simple compared to the many other approaches.

I am wondering if the Javascript code produced can easily be consumed as a library. I need to use it with react and react native.

Also who can initiate calling who ? I ask because this one https://github.com/dustywilson/gopherjs-rpc, say the Server can call the Client ONLY.

Kind of confusing. For example, can the Client initiate calls too ?

thanks allot

**Comment by utamaro** [comment]
Sorry for my late response.

1. I only checked wsrpc with golang, so  I don't know you can use it with websocket/rpc in react(?).
    I think it depends on specification of gopherjs .

2. hmm,, I can call server funcs from client AND client funcs from server ....

**Comment by joeblew99** [comment]
its ok. i got it working... thanks

**Comment by joeblew99** [comment]
I ended up using Polymer, and not react btw. 
I have used polymer for 1 year, and in the last 3 months its really fast at runtime.
Just saying that its nice.
