### ISSUE TITLE
embedded assets

### ISSUE THREAD

**Issue by joeblew99** [utamaro/wsrpc#4]
I would like to be able to embed the assets.

This package is one that can do it, and its design seems good:
https://github.com/shurcooL/vfsgen

But i am having trouble getting the web server to respect it.
I think the best place to serve assets from is the common go file here:
wsrpc/webserver/webserver.go

**Comment by utamaro** [comment]
I guess you can simply make  assets_vfsdata.go file by vfsgen and add a below line to  webserver.go:
   http.Handle("/assets/", http.FileServer(assets)) //in func start

Doesn't it work well?

I didn't use vfsgen, and didn't try this one,  just a guess.

**Comment by joeblew99** [comment]
i got it working in the end.

The problem is that the web sockets RPC cant be easily chained to other handlers.
I dont think i can make a PR on this because i ripped everything up.

I am trying out GRPC with GRPC Gateway code, and seeing how well it works with gopherjs for client stuff.
